// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	emailFieldNames          = builder.RawFieldNames(&Email{})
	emailRows                = strings.Join(emailFieldNames, ",")
	emailRowsExpectAutoSet   = strings.Join(stringx.Remove(emailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	emailRowsWithPlaceHolder = strings.Join(stringx.Remove(emailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	emailModel interface {
		Insert(ctx context.Context, data *Email) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Email, error)
		Update(ctx context.Context, data *Email) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEmailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Email struct {
		Id       int64          `db:"id"`
		UserId   int64          `db:"user_id"`
		Email    sql.NullString `db:"email"`
		IsDelete bool           `db:"is_delete"`
		CreateAt time.Time      `db:"create_at"`
		DeleteAt sql.NullTime   `db:"delete_at"`
	}
)

func newEmailModel(conn sqlx.SqlConn) *defaultEmailModel {
	return &defaultEmailModel{
		conn:  conn,
		table: "`email`",
	}
}

func (m *defaultEmailModel) withSession(session sqlx.Session) *defaultEmailModel {
	return &defaultEmailModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`email`",
	}
}

func (m *defaultEmailModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEmailModel) FindOne(ctx context.Context, id int64) (*Email, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", emailRows, m.table)
	var resp Email
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEmailModel) Insert(ctx context.Context, data *Email) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, emailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Email, data.IsDelete, data.DeleteAt)
	return ret, err
}

func (m *defaultEmailModel) Update(ctx context.Context, data *Email) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, emailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Email, data.IsDelete, data.DeleteAt, data.Id)
	return err
}

func (m *defaultEmailModel) tableName() string {
	return m.table
}
