// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	footerFieldNames          = builder.RawFieldNames(&Footer{})
	footerRows                = strings.Join(footerFieldNames, ",")
	footerRowsExpectAutoSet   = strings.Join(stringx.Remove(footerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	footerRowsWithPlaceHolder = strings.Join(stringx.Remove(footerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	footerModel interface {
		Insert(ctx context.Context, data *Footer) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Footer, error)
		Update(ctx context.Context, data *Footer) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFooterModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Footer struct {
		Id        int64     `db:"id"`
		Copyright string    `db:"copyright"`
		Icp1      string    `db:"icp1"`
		Icp2      string    `db:"icp2"`
		Gongan    string    `db:"gongan"`
		CreateAt  time.Time `db:"create_at"`
	}
)

func newFooterModel(conn sqlx.SqlConn) *defaultFooterModel {
	return &defaultFooterModel{
		conn:  conn,
		table: "`footer`",
	}
}

func (m *defaultFooterModel) withSession(session sqlx.Session) *defaultFooterModel {
	return &defaultFooterModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`footer`",
	}
}

func (m *defaultFooterModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFooterModel) FindOne(ctx context.Context, id int64) (*Footer, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", footerRows, m.table)
	var resp Footer
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFooterModel) Insert(ctx context.Context, data *Footer) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, footerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Copyright, data.Icp1, data.Icp2, data.Gongan)
	return ret, err
}

func (m *defaultFooterModel) Update(ctx context.Context, data *Footer) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, footerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Copyright, data.Icp1, data.Icp2, data.Gongan, data.Id)
	return err
}

func (m *defaultFooterModel) tableName() string {
	return m.table
}
