// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	headerFieldNames          = builder.RawFieldNames(&Header{})
	headerRows                = strings.Join(headerFieldNames, ",")
	headerRowsExpectAutoSet   = strings.Join(stringx.Remove(headerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	headerRowsWithPlaceHolder = strings.Join(stringx.Remove(headerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	headerModel interface {
		Insert(ctx context.Context, data *Header) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Header, error)
		Update(ctx context.Context, data *Header) error
		Delete(ctx context.Context, id int64) error
	}

	defaultHeaderModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Header struct {
		Id       int64          `db:"id"`
		UserId   int64          `db:"user_id"`
		Header   sql.NullString `db:"header"`
		CreateAt time.Time      `db:"create_at"`
		DeleteAt sql.NullTime   `db:"delete_at"`
	}
)

func newHeaderModel(conn sqlx.SqlConn) *defaultHeaderModel {
	return &defaultHeaderModel{
		conn:  conn,
		table: "`header`",
	}
}

func (m *defaultHeaderModel) withSession(session sqlx.Session) *defaultHeaderModel {
	return &defaultHeaderModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`header`",
	}
}

func (m *defaultHeaderModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultHeaderModel) FindOne(ctx context.Context, id int64) (*Header, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", headerRows, m.table)
	var resp Header
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHeaderModel) Insert(ctx context.Context, data *Header) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, headerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Header, data.DeleteAt)
	return ret, err
}

func (m *defaultHeaderModel) Update(ctx context.Context, data *Header) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, headerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Header, data.DeleteAt, data.Id)
	return err
}

func (m *defaultHeaderModel) tableName() string {
	return m.table
}
