// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	loginControllerFieldNames          = builder.RawFieldNames(&LoginController{})
	loginControllerRows                = strings.Join(loginControllerFieldNames, ",")
	loginControllerRowsExpectAutoSet   = strings.Join(stringx.Remove(loginControllerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loginControllerRowsWithPlaceHolder = strings.Join(stringx.Remove(loginControllerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	loginControllerModel interface {
		Insert(ctx context.Context, data *LoginController) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LoginController, error)
		Update(ctx context.Context, data *LoginController) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLoginControllerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	LoginController struct {
		Id            int64        `db:"id"`
		UserId        int64        `db:"user_id"`
		AllowPhone    bool         `db:"allow_phone"`
		AllowEmail    bool         `db:"allow_email"`
		AllowWechat   bool         `db:"allow_wechat"`
		AllowPassword bool         `db:"allow_password"`
		Allow2Fa      bool         `db:"allow_2fa"`
		CreateAt      time.Time    `db:"create_at"`
		DeleteAt      sql.NullTime `db:"delete_at"`
	}
)

func newLoginControllerModel(conn sqlx.SqlConn) *defaultLoginControllerModel {
	return &defaultLoginControllerModel{
		conn:  conn,
		table: "`login_controller`",
	}
}

func (m *defaultLoginControllerModel) withSession(session sqlx.Session) *defaultLoginControllerModel {
	return &defaultLoginControllerModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`login_controller`",
	}
}

func (m *defaultLoginControllerModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultLoginControllerModel) FindOne(ctx context.Context, id int64) (*LoginController, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginControllerRows, m.table)
	var resp LoginController
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoginControllerModel) Insert(ctx context.Context, data *LoginController) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, loginControllerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AllowPhone, data.AllowEmail, data.AllowWechat, data.AllowPassword, data.Allow2Fa, data.DeleteAt)
	return ret, err
}

func (m *defaultLoginControllerModel) Update(ctx context.Context, data *LoginController) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, loginControllerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.AllowPhone, data.AllowEmail, data.AllowWechat, data.AllowPassword, data.Allow2Fa, data.DeleteAt, data.Id)
	return err
}

func (m *defaultLoginControllerModel) tableName() string {
	return m.table
}
