// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	nicknameFieldNames          = builder.RawFieldNames(&Nickname{})
	nicknameRows                = strings.Join(nicknameFieldNames, ",")
	nicknameRowsExpectAutoSet   = strings.Join(stringx.Remove(nicknameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	nicknameRowsWithPlaceHolder = strings.Join(stringx.Remove(nicknameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	nicknameModel interface {
		Insert(ctx context.Context, data *Nickname) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Nickname, error)
		Update(ctx context.Context, data *Nickname) error
		Delete(ctx context.Context, id int64) error
	}

	defaultNicknameModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Nickname struct {
		Id       int64          `db:"id"`
		UserId   int64          `db:"user_id"`
		Nickname sql.NullString `db:"nickname"`
		CreateAt time.Time      `db:"create_at"`
		DeleteAt sql.NullTime   `db:"delete_at"`
	}
)

func newNicknameModel(conn sqlx.SqlConn) *defaultNicknameModel {
	return &defaultNicknameModel{
		conn:  conn,
		table: "`nickname`",
	}
}

func (m *defaultNicknameModel) withSession(session sqlx.Session) *defaultNicknameModel {
	return &defaultNicknameModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`nickname`",
	}
}

func (m *defaultNicknameModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultNicknameModel) FindOne(ctx context.Context, id int64) (*Nickname, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", nicknameRows, m.table)
	var resp Nickname
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultNicknameModel) Insert(ctx context.Context, data *Nickname) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, nicknameRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Nickname, data.DeleteAt)
	return ret, err
}

func (m *defaultNicknameModel) Update(ctx context.Context, data *Nickname) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, nicknameRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Nickname, data.DeleteAt, data.Id)
	return err
}

func (m *defaultNicknameModel) tableName() string {
	return m.table
}
