// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	oauth2RecordFieldNames          = builder.RawFieldNames(&Oauth2Record{})
	oauth2RecordRows                = strings.Join(oauth2RecordFieldNames, ",")
	oauth2RecordRowsExpectAutoSet   = strings.Join(stringx.Remove(oauth2RecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	oauth2RecordRowsWithPlaceHolder = strings.Join(stringx.Remove(oauth2RecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	oauth2RecordModel interface {
		Insert(ctx context.Context, data *Oauth2Record) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Oauth2Record, error)
		Update(ctx context.Context, data *Oauth2Record) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOauth2RecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Oauth2Record struct {
		Id        int64        `db:"id"`
		UserId    int64        `db:"user_id"`
		WebId     int64        `db:"web_id"`
		WebName   string       `db:"web_name"`
		Ip        string       `db:"ip"`
		Geo       string       `db:"geo"`
		GeoCode   string       `db:"geo_code"`
		CreateAt  time.Time    `db:"create_at"`
		LoginTime time.Time    `db:"login_time"`
		DeleteAt  sql.NullTime `db:"delete_at"`
	}
)

func newOauth2RecordModel(conn sqlx.SqlConn) *defaultOauth2RecordModel {
	return &defaultOauth2RecordModel{
		conn:  conn,
		table: "`oauth2_record`",
	}
}

func (m *defaultOauth2RecordModel) withSession(session sqlx.Session) *defaultOauth2RecordModel {
	return &defaultOauth2RecordModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`oauth2_record`",
	}
}

func (m *defaultOauth2RecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOauth2RecordModel) FindOne(ctx context.Context, id int64) (*Oauth2Record, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", oauth2RecordRows, m.table)
	var resp Oauth2Record
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOauth2RecordModel) Insert(ctx context.Context, data *Oauth2Record) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, oauth2RecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.WebId, data.WebName, data.Ip, data.Geo, data.GeoCode, data.LoginTime, data.DeleteAt)
	return ret, err
}

func (m *defaultOauth2RecordModel) Update(ctx context.Context, data *Oauth2Record) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, oauth2RecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.WebId, data.WebName, data.Ip, data.Geo, data.GeoCode, data.LoginTime, data.DeleteAt, data.Id)
	return err
}

func (m *defaultOauth2RecordModel) tableName() string {
	return m.table
}
