// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	ossFileFieldNames          = builder.RawFieldNames(&OssFile{})
	ossFileRows                = strings.Join(ossFileFieldNames, ",")
	ossFileRowsExpectAutoSet   = strings.Join(stringx.Remove(ossFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ossFileRowsWithPlaceHolder = strings.Join(stringx.Remove(ossFileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ossFileModel interface {
		Insert(ctx context.Context, data *OssFile) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OssFile, error)
		Update(ctx context.Context, data *OssFile) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOssFileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OssFile struct {
		Id        int64        `db:"id"`
		Fid       string       `db:"fid"`
		Key       string       `db:"key"`
		MediaType string       `db:"media_type"`
		CreateAt  time.Time    `db:"create_at"`
		DeleteAt  sql.NullTime `db:"delete_at"`
	}
)

func newOssFileModel(conn sqlx.SqlConn) *defaultOssFileModel {
	return &defaultOssFileModel{
		conn:  conn,
		table: "`oss_file`",
	}
}

func (m *defaultOssFileModel) withSession(session sqlx.Session) *defaultOssFileModel {
	return &defaultOssFileModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`oss_file`",
	}
}

func (m *defaultOssFileModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOssFileModel) FindOne(ctx context.Context, id int64) (*OssFile, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ossFileRows, m.table)
	var resp OssFile
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOssFileModel) Insert(ctx context.Context, data *OssFile) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, ossFileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Fid, data.Key, data.MediaType, data.DeleteAt)
	return ret, err
}

func (m *defaultOssFileModel) Update(ctx context.Context, data *OssFile) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ossFileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Fid, data.Key, data.MediaType, data.DeleteAt, data.Id)
	return err
}

func (m *defaultOssFileModel) tableName() string {
	return m.table
}
