// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	smsMessageFieldNames          = builder.RawFieldNames(&SmsMessage{})
	smsMessageRows                = strings.Join(smsMessageFieldNames, ",")
	smsMessageRowsExpectAutoSet   = strings.Join(stringx.Remove(smsMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	smsMessageRowsWithPlaceHolder = strings.Join(stringx.Remove(smsMessageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	smsMessageModel interface {
		Insert(ctx context.Context, data *SmsMessage) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SmsMessage, error)
		Update(ctx context.Context, data *SmsMessage) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSmsMessageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SmsMessage struct {
		Id            int64          `db:"id"`
		Phone         string         `db:"phone"`
		Sig           string         `db:"sig"`
		Template      string         `db:"template"`
		TemplateParam string         `db:"template_param"`
		SenderId      int64          `db:"sender_id"`
		Success       bool           `db:"success"`
		ErrorMsg      sql.NullString `db:"error_msg"`
		CreateAt      time.Time      `db:"create_at"`
		DeleteAt      sql.NullTime   `db:"delete_at"`
	}
)

func newSmsMessageModel(conn sqlx.SqlConn) *defaultSmsMessageModel {
	return &defaultSmsMessageModel{
		conn:  conn,
		table: "`sms_message`",
	}
}

func (m *defaultSmsMessageModel) withSession(session sqlx.Session) *defaultSmsMessageModel {
	return &defaultSmsMessageModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`sms_message`",
	}
}

func (m *defaultSmsMessageModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSmsMessageModel) FindOne(ctx context.Context, id int64) (*SmsMessage, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", smsMessageRows, m.table)
	var resp SmsMessage
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSmsMessageModel) Insert(ctx context.Context, data *SmsMessage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, smsMessageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Sig, data.Template, data.TemplateParam, data.SenderId, data.Success, data.ErrorMsg, data.DeleteAt)
	return ret, err
}

func (m *defaultSmsMessageModel) Update(ctx context.Context, data *SmsMessage) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, smsMessageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Sig, data.Template, data.TemplateParam, data.SenderId, data.Success, data.ErrorMsg, data.DeleteAt, data.Id)
	return err
}

func (m *defaultSmsMessageModel) tableName() string {
	return m.table
}
