// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	titleFieldNames          = builder.RawFieldNames(&Title{})
	titleRows                = strings.Join(titleFieldNames, ",")
	titleRowsExpectAutoSet   = strings.Join(stringx.Remove(titleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	titleRowsWithPlaceHolder = strings.Join(stringx.Remove(titleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	titleModel interface {
		Insert(ctx context.Context, data *Title) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Title, error)
		Update(ctx context.Context, data *Title) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTitleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Title struct {
		Id       int64          `db:"id"`
		UserId   int64          `db:"user_id"`
		Name     sql.NullString `db:"name"`
		TaxId    sql.NullString `db:"tax_id"`
		BankId   sql.NullString `db:"bank_id"`
		Bank     sql.NullString `db:"bank"`
		CreateAt time.Time      `db:"create_at"`
		DeleteAt sql.NullTime   `db:"delete_at"`
	}
)

func newTitleModel(conn sqlx.SqlConn) *defaultTitleModel {
	return &defaultTitleModel{
		conn:  conn,
		table: "`title`",
	}
}

func (m *defaultTitleModel) withSession(session sqlx.Session) *defaultTitleModel {
	return &defaultTitleModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`title`",
	}
}

func (m *defaultTitleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTitleModel) FindOne(ctx context.Context, id int64) (*Title, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", titleRows, m.table)
	var resp Title
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTitleModel) Insert(ctx context.Context, data *Title) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, titleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.TaxId, data.BankId, data.Bank, data.DeleteAt)
	return ret, err
}

func (m *defaultTitleModel) Update(ctx context.Context, data *Title) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, titleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.TaxId, data.BankId, data.Bank, data.DeleteAt, data.Id)
	return err
}

func (m *defaultTitleModel) tableName() string {
	return m.table
}
