// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	uncleFieldNames          = builder.RawFieldNames(&Uncle{})
	uncleRows                = strings.Join(uncleFieldNames, ",")
	uncleRowsExpectAutoSet   = strings.Join(stringx.Remove(uncleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	uncleRowsWithPlaceHolder = strings.Join(stringx.Remove(uncleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	uncleModel interface {
		Insert(ctx context.Context, data *Uncle) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Uncle, error)
		FindOneByUserIdUncleIdDeleteAt(ctx context.Context, userId int64, uncleId int64, deleteAt sql.NullTime) (*Uncle, error)
		Update(ctx context.Context, data *Uncle) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUncleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Uncle struct {
		Id       int64        `db:"id"`
		UserId   int64        `db:"user_id"`
		UncleId  int64        `db:"uncle_id"`
		UncleTag string       `db:"uncle_tag"`
		Status   int64        `db:"status"`
		CreateAt time.Time    `db:"create_at"`
		DeleteAt sql.NullTime `db:"delete_at"`
	}
)

func newUncleModel(conn sqlx.SqlConn) *defaultUncleModel {
	return &defaultUncleModel{
		conn:  conn,
		table: "`uncle`",
	}
}

func (m *defaultUncleModel) withSession(session sqlx.Session) *defaultUncleModel {
	return &defaultUncleModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`uncle`",
	}
}

func (m *defaultUncleModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUncleModel) FindOne(ctx context.Context, id int64) (*Uncle, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", uncleRows, m.table)
	var resp Uncle
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUncleModel) FindOneByUserIdUncleIdDeleteAt(ctx context.Context, userId int64, uncleId int64, deleteAt sql.NullTime) (*Uncle, error) {
	var resp Uncle
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `uncle_id` = ? and `delete_at` = ? limit 1", uncleRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, uncleId, deleteAt)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUncleModel) Insert(ctx context.Context, data *Uncle) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, uncleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.UncleId, data.UncleTag, data.Status, data.DeleteAt)
	return ret, err
}

func (m *defaultUncleModel) Update(ctx context.Context, newData *Uncle) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, uncleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.UncleId, newData.UncleTag, newData.Status, newData.DeleteAt, newData.Id)
	return err
}

func (m *defaultUncleModel) tableName() string {
	return m.table
}
