// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	usernameFieldNames          = builder.RawFieldNames(&Username{})
	usernameRows                = strings.Join(usernameFieldNames, ",")
	usernameRowsExpectAutoSet   = strings.Join(stringx.Remove(usernameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usernameRowsWithPlaceHolder = strings.Join(stringx.Remove(usernameFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	usernameModel interface {
		Insert(ctx context.Context, data *Username) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Username, error)
		Update(ctx context.Context, data *Username) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUsernameModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Username struct {
		Id       int64          `db:"id"`
		UserId   int64          `db:"user_id"`
		Username sql.NullString `db:"username"`
		IsDelete bool           `db:"is_delete"`
		CreateAt time.Time      `db:"create_at"`
		DeleteAt sql.NullTime   `db:"delete_at"`
	}
)

func newUsernameModel(conn sqlx.SqlConn) *defaultUsernameModel {
	return &defaultUsernameModel{
		conn:  conn,
		table: "`username`",
	}
}

func (m *defaultUsernameModel) withSession(session sqlx.Session) *defaultUsernameModel {
	return &defaultUsernameModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`username`",
	}
}

func (m *defaultUsernameModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUsernameModel) FindOne(ctx context.Context, id int64) (*Username, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", usernameRows, m.table)
	var resp Username
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsernameModel) Insert(ctx context.Context, data *Username) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, usernameRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.IsDelete, data.DeleteAt)
	return ret, err
}

func (m *defaultUsernameModel) Update(ctx context.Context, data *Username) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, usernameRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Username, data.IsDelete, data.DeleteAt, data.Id)
	return err
}

func (m *defaultUsernameModel) tableName() string {
	return m.table
}
