// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	websiteIpFieldNames          = builder.RawFieldNames(&WebsiteIp{})
	websiteIpRows                = strings.Join(websiteIpFieldNames, ",")
	websiteIpRowsExpectAutoSet   = strings.Join(stringx.Remove(websiteIpFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	websiteIpRowsWithPlaceHolder = strings.Join(stringx.Remove(websiteIpFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	websiteIpModel interface {
		Insert(ctx context.Context, data *WebsiteIp) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WebsiteIp, error)
		Update(ctx context.Context, data *WebsiteIp) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWebsiteIpModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WebsiteIp struct {
		Id        int64        `db:"id"`
		WebsiteId int64        `db:"website_id"`
		Ip        string       `db:"ip"`
		CreateAt  time.Time    `db:"create_at"`
		DeleteAt  sql.NullTime `db:"delete_at"`
	}
)

func newWebsiteIpModel(conn sqlx.SqlConn) *defaultWebsiteIpModel {
	return &defaultWebsiteIpModel{
		conn:  conn,
		table: "`website_ip`",
	}
}

func (m *defaultWebsiteIpModel) withSession(session sqlx.Session) *defaultWebsiteIpModel {
	return &defaultWebsiteIpModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`website_ip`",
	}
}

func (m *defaultWebsiteIpModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWebsiteIpModel) FindOne(ctx context.Context, id int64) (*WebsiteIp, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", websiteIpRows, m.table)
	var resp WebsiteIp
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWebsiteIpModel) Insert(ctx context.Context, data *WebsiteIp) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, websiteIpRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WebsiteId, data.Ip, data.DeleteAt)
	return ret, err
}

func (m *defaultWebsiteIpModel) Update(ctx context.Context, data *WebsiteIp) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, websiteIpRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.WebsiteId, data.Ip, data.DeleteAt, data.Id)
	return err
}

func (m *defaultWebsiteIpModel) tableName() string {
	return m.table
}
