// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	websiteDomainFieldNames          = builder.RawFieldNames(&WebsiteDomain{})
	websiteDomainRows                = strings.Join(websiteDomainFieldNames, ",")
	websiteDomainRowsExpectAutoSet   = strings.Join(stringx.Remove(websiteDomainFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	websiteDomainRowsWithPlaceHolder = strings.Join(stringx.Remove(websiteDomainFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	websiteDomainModel interface {
		Insert(ctx context.Context, data *WebsiteDomain) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WebsiteDomain, error)
		Update(ctx context.Context, data *WebsiteDomain) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWebsiteDomainModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WebsiteDomain struct {
		Id        int64        `db:"id"`
		WebsiteId int64        `db:"website_id"`
		Domain    string       `db:"domain"`
		CreateAt  time.Time    `db:"create_at"`
		DeleteAt  sql.NullTime `db:"delete_at"`
	}
)

func newWebsiteDomainModel(conn sqlx.SqlConn) *defaultWebsiteDomainModel {
	return &defaultWebsiteDomainModel{
		conn:  conn,
		table: "`website_domain`",
	}
}

func (m *defaultWebsiteDomainModel) withSession(session sqlx.Session) *defaultWebsiteDomainModel {
	return &defaultWebsiteDomainModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`website_domain`",
	}
}

func (m *defaultWebsiteDomainModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWebsiteDomainModel) FindOne(ctx context.Context, id int64) (*WebsiteDomain, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", websiteDomainRows, m.table)
	var resp WebsiteDomain
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWebsiteDomainModel) Insert(ctx context.Context, data *WebsiteDomain) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, websiteDomainRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WebsiteId, data.Domain, data.DeleteAt)
	return ret, err
}

func (m *defaultWebsiteDomainModel) Update(ctx context.Context, data *WebsiteDomain) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, websiteDomainRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.WebsiteId, data.Domain, data.DeleteAt, data.Id)
	return err
}

func (m *defaultWebsiteDomainModel) tableName() string {
	return m.table
}
