// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	workOrderCommunicateFieldNames          = builder.RawFieldNames(&WorkOrderCommunicate{})
	workOrderCommunicateRows                = strings.Join(workOrderCommunicateFieldNames, ",")
	workOrderCommunicateRowsExpectAutoSet   = strings.Join(stringx.Remove(workOrderCommunicateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workOrderCommunicateRowsWithPlaceHolder = strings.Join(stringx.Remove(workOrderCommunicateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workOrderCommunicateModel interface {
		Insert(ctx context.Context, data *WorkOrderCommunicate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WorkOrderCommunicate, error)
		Update(ctx context.Context, data *WorkOrderCommunicate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWorkOrderCommunicateModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkOrderCommunicate struct {
		Id       int64        `db:"id"`
		OrderId  int64        `db:"order_id"`
		Content  string       `db:"content"`
		From     int64        `db:"from"`
		CreateAt time.Time    `db:"create_at"`
		DeleteAt sql.NullTime `db:"delete_at"`
	}
)

func newWorkOrderCommunicateModel(conn sqlx.SqlConn) *defaultWorkOrderCommunicateModel {
	return &defaultWorkOrderCommunicateModel{
		conn:  conn,
		table: "`work_order_communicate`",
	}
}

func (m *defaultWorkOrderCommunicateModel) withSession(session sqlx.Session) *defaultWorkOrderCommunicateModel {
	return &defaultWorkOrderCommunicateModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`work_order_communicate`",
	}
}

func (m *defaultWorkOrderCommunicateModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkOrderCommunicateModel) FindOne(ctx context.Context, id int64) (*WorkOrderCommunicate, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workOrderCommunicateRows, m.table)
	var resp WorkOrderCommunicate
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkOrderCommunicateModel) Insert(ctx context.Context, data *WorkOrderCommunicate) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, workOrderCommunicateRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderId, data.Content, data.From, data.DeleteAt)
	return ret, err
}

func (m *defaultWorkOrderCommunicateModel) Update(ctx context.Context, data *WorkOrderCommunicate) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workOrderCommunicateRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderId, data.Content, data.From, data.DeleteAt, data.Id)
	return err
}

func (m *defaultWorkOrderCommunicateModel) tableName() string {
	return m.table
}
