// Code generated by goctlwt. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/wuntsong-org/go-zero-plus/core/stores/builder"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlc"
	"github.com/wuntsong-org/go-zero-plus/core/stores/sqlx"
	"github.com/wuntsong-org/go-zero-plus/core/stringx"
)

var (
	wxrobotFieldNames          = builder.RawFieldNames(&Wxrobot{})
	wxrobotRows                = strings.Join(wxrobotFieldNames, ",")
	wxrobotRowsExpectAutoSet   = strings.Join(stringx.Remove(wxrobotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	wxrobotRowsWithPlaceHolder = strings.Join(stringx.Remove(wxrobotFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	wxrobotModel interface {
		Insert(ctx context.Context, data *Wxrobot) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Wxrobot, error)
		Update(ctx context.Context, data *Wxrobot) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWxrobotModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Wxrobot struct {
		Id       int64          `db:"id"`
		UserId   int64          `db:"user_id"`
		Webhook  sql.NullString `db:"webhook"`
		CreateAt time.Time      `db:"create_at"`
		DeleteAt sql.NullTime   `db:"delete_at"`
	}
)

func newWxrobotModel(conn sqlx.SqlConn) *defaultWxrobotModel {
	return &defaultWxrobotModel{
		conn:  conn,
		table: "`wxrobot`",
	}
}

func (m *defaultWxrobotModel) withSession(session sqlx.Session) *defaultWxrobotModel {
	return &defaultWxrobotModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`wxrobot`",
	}
}

func (m *defaultWxrobotModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWxrobotModel) FindOne(ctx context.Context, id int64) (*Wxrobot, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", wxrobotRows, m.table)
	var resp Wxrobot
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWxrobotModel) Insert(ctx context.Context, data *Wxrobot) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, wxrobotRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Webhook, data.DeleteAt)
	return ret, err
}

func (m *defaultWxrobotModel) Update(ctx context.Context, data *Wxrobot) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, wxrobotRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Webhook, data.DeleteAt, data.Id)
	return err
}

func (m *defaultWxrobotModel) tableName() string {
	return m.table
}
